### ISSUE TITLE
Do not assume envelope is in sustain phase when noteOff is called

### ISSUE THREAD

**Issue by svgeesus** [PaulStoffregen/Audio#108] opened 2015-02-19 11:12 UTC
Details here
https://forum.pjrc.com/threads/27806-Clicking-envelope-with-Audio-Library?p=65273&viewfull=1#post65273

**Comment by Nantonos** [comment] 2015-02-19 12:20
and the corollary, do not assume envelope is in idle phase when noteOn is called. Both assumptions result in discontinuous, immediate changes to the mult variable which holds the current attenuation level, causing clicks.

**Comment by PaulStoffregen** [comment] 2015-09-13 01:12
Duplicate of #107

**Closed** 2015-09-13 01:12 UTC
Labels: duplicate
