### ISSUE TITLE
AudioEffectEnvelope slope times limited to 200 ms

### ISSUE THREAD

**Issue by DavidMenting** [PaulStoffregen/Audio#158] opened 2016-01-21 09:50 UTC
In effect_envelope.h the length of each slope in the envelope is hard limited to 200 ms. This is a very low limit for musical uses.

Is there a specific reason for this limit? Is there any harm in removing the limit? Commenting out the limit in effect_envelope.h solves the issue for me now, but I'm sure other people run into this as well.

**Comment by PaulStoffregen** [comment] 2016-01-21 11:59
This is a duplicate of #102

Please give the code on #142 a try.  Does it work for you?

When I work on this again, I also want to consider #107.  All of these are related to the numerical precision of the algorithm.

**Closed by PaulStoffregen** 2016-01-21 11:59 UTC

**Comment by PaulStoffregen** [comment] 2017-05-04 13:09
fixed
